Frogging-Family/linux-tkg

linux54-tkg/PKGBUILD
linux56-tkg/PKGBUILD
linux57-tkg/PKGBUILD

I personally prefer to symlink the folder containing the kernel `PKGBUILD`
among other files to somewhere else for quicker access and with that
setup `.myfrag` config fragments were not getting found earlier.

linux5*-tkg: Fix finding config fragments when $_where is a symlink

---

linux57-tkg/customization.cfg
linux58-rc-tkg/customization.cfg

These lines seem to have been left behind. [`linux56-tkg`](https://github.com/Frogging-Family/linux-tkg/blob/14df411ac59ed7cef254a21732f27b904c336d99/linux56-tkg/customization.cfg#L26-L27) for reference.

linux57/58-tkg: Add _noccache to default cfg.

---

.gitignore

[`makepkg.conf(5)`](https://www.archlinux.org/pacman/makepkg.conf.5.html) supports several different package extensions. The current `.gitignore` accounts for zstd and gz compression, but not for a lack of compression (`*.tar`), which is useful for smaller build times. Rather than adding another extension, I think it's best to match the `.pkg` part. I can add `*.src.*` too, it's just unclear to me whether or not that's useful here.

gitignore: Ignore all package extensions.

---

linux57-tkg/customization.cfg
linux57-tkg/linux57-tkg-config/prepare

I think this is a quality of life improvement for the end user, especially Ubuntu guys (maybe Fedora, I started working on it, I will see if it gets those leak errors), since they will for sure go through the compile process once with `_misc_adds=true`, see that it doesn't work. Try to find out why, and then maybe end up trying `_misc_adds=false`. 
I believe having the prompt would help. What do you think ?
Edit: Fedora gets the leaky TTY too, maybe I should work on a fix for the leak, like PDS actually

linux57: add interactive prompt for _misc_adds

---

linux54-tkg/linux54-tkg-config/prepare
linux57-tkg/linux57-tkg-config/prepare
linux58-tkg/linux58-tkg-config/prepare
linux59-rc-tkg/linux59-tkg-config/prepare

This PR pipes `yes ""` to `make localmodconfig`, to alleviate Tk-Glitch/PKGBUILDS#404. I deem this to be an acceptable solution as this seems to be "not our bug" as this affects more than TkG, and the options that are prompted for seem to be pretty insignificant.

Accept default options to "make localmodconfig"

---

linux54-tkg/PKGBUILD
linux54-tkg/README.md
linux57-tkg/PKGBUILD
linux57-tkg/README.md
linux58-tkg/PKGBUILD
linux58-tkg/README.md
linux59-rc-tkg/PKGBUILD
linux59-rc-tkg/README.md

This pull request adds basic functionality for saving TkG variables (variables preceded with a `_`) to a file, and installing that file to the system. This can be useful for testing different kernel configurations, and seeing what the current version was compiled with. I have only implemented this for 5.7 as there are some design concerns that are up in the air:
- As is, `hackheaders` removes documentation from the package, so the only "documentation" produced by linux-tkg in this PR is `/usr/share/doc/${pkgbase}/customization.cfg`. As such, if one has `options=(!docs)` in their `makepkg.conf`, here it would only serve to strip that `customization.cfg`, so I have overrode that.
- Is it desired behavior to produce this file if even if someone has `options=(!docs)`?
- Would this file belong …

Install the TkG configuration used to the system

---

linux58-tkg/customization.cfg
linux58-tkg/install.sh

I only applied it in version 5.8 so that first you can see if it applies to all, or if my solution is viable.
The problem is that every time it does the verification, it downloads the original configuration from github and does not maintain its own manual configuration that solves the certificate problem in Debian, it does not finish compiling for that reason.
And when you give Install.sh the CONFIG_SYSTEM_TRUSTED_KEYS = "debian / certs / test-signing-certs.pem" is reset, regardless of whether you edited it.

Fix certificate issue on Debian

---

linux57-tkg/linux57-tkg-config/prepare
linux58-tkg/linux58-tkg-config/prepare
linux59-rc-tkg/linux59-tkg-config/prepare

This PR fixes #64 
The `install.sh` script cleans up by itself what's in the linux git folder and does not need cleaning up. And it was affecting the `config` feature it offered of patching&configuring the git folder and leaving it in that state so the user can compile it in the way he likes.

Fix cleanup step on non-arch distros

---

linux59-rc-tkg/install.sh

Fixes #58 
Marginally tested. Builds, creates the RPMs and works fine when building.
Also installs the kernel fine.
Please someone test in Debian, don't have any debian-based machine to test :(
Confirmed to work in Fedora.
Fully reusable for future -RCs.

Add initial -rc support to the install.sh script.

---

linux57-tkg/install.sh
linux58-tkg/install.sh
linux59-rc-tkg/install.sh

Reason that the compilation fails due to the need for this certificate, it is not necessary and only causes problems

Fix build fail certificate UEFI on Debian 5.7/5.8/5.9rc

---

linux-tkg/linux-tkg-config/prepare

There is one additional "-" which shouldn't be here.

linux-tkg: cosmetics in localversion if using llvm

---

install.sh

Split Debian and Ubuntu build dependencies, as "kernel-package" is not
available, but also not needed in newer Debian releases.
Add some other dependencies dpkg-buildpackage was complaining about.
With these dependencies the tkg kernel builds in a freshly bootstrapped
Debian "Buster" container.

update Debian build dependencies in "install.sh"

---

install.sh

source 'customization.cfg' before '_tkg_initscript' is run in
'install.sh'. Otherwise some variables set in 'customization.cfg' are
empty when '_tkg_initscript' is run and have to be supplied again on the
prompt.

source 'customization.cfg' earlier in 'install.sh'

---

linux-tkg-config/prepare

also move Void LibreSSL out of noccache check so it still runs if ccache
is set off
Thanks to @Kodehawa for pointing this out, since LLVM11 is on Arch now :frog:

llvm: Fix kcsan prompt showing since we don't want kcsan

---

PKGBUILD
linux-tkg-config/prepare
linux-tkg-patches/5.10/0013-v5.10-rc7-revert.patch

This adds a patch to revert the commit https://github.com/torvalds/linux/commit/3351b16af4946fff0d46481d155fb91adb28b1f9, which causes a compilation issue on the latest release candidate and fixes #134

Add patch to fix compilation issue on 5.10-rc7

---

PKGBUILD

I got an error "make[1]: *** [kernel/Makefile:146: kernel/kheaders_data.tar.xz] Error 127" when compiling 5.10.4. According to https://bbs.archlinux.org/viewtopic.php?id=261876 "cpio" package is needed. Installing that fixed the problem.

add cpio as make depend

---

PKGBUILD

It was decided [here](https://github.com/Frogging-Family/linux-tkg/pull/49#issuecomment-677631969) that we would like to not include the build path in the built package. This PR upholds this by adding an exception for `$_path` to `customization-full.cfg`.
Cheers ^.^

Blacklist $_path from installed config

---

linux-tkg-config/prepare

Hello!
I simplified the `-march=XX` code path with an array. I retested the graysky patch with LLVM and it works without any issue, the kernel compiles and the clang compiler does receive the `-march=xx` option. I also [reported](https://github.com/graysky2/kernel_gcc_patch/issues/57) it in an issue on graysky's repository.
See ya for another PR,
Adel

Simplify cpu marchs and enable for LLVM

---

PKGBUILD

after that it can be removed from nvidia-tkg

add pahole dependency to headers on 5.11+

---

customization.cfg
install.sh

Hello,
I added the `googlesource.com` mirror to `install.sh`, this should close #181. I also refactored the `sub=0` code path into fewer lines. I will PR later on the ability to use `tar` source code if people wish to use the `/tmp` ramfs folder.
Adel

install.sh: add googlesource.com git mirror and code cleanup

---

PKGBUILD

The urls for graysky2's cpu opt patchests have been changed, see [this commit](https://github.com/graysky2/kernel_gcc_patch/commit/5fa7fc7802c929eb239198adabcfc42ee852065b), causing the script to fail on downloading them, this updates them to the new versions.

Fix urls for graysky2's cpu opt patchsets

---

customization.cfg
install.sh
linux-tkg-config/prepare

Hello!
Some extra features that I personally find handy:
- Have the script copy the generated `.config` file next to the PKGBUILD, as `.config.new` so I can save it somewhere, after I did some various changes with `make xconfig`. I find the final `.config` file more useful than frags because the originally used `.config` file is not constant in non arch. 
- With the previous feature, the next step is to enable `install.sh` to use such custom `.config` files.
- Fixed an issue with `install.sh` where the prompt for the kernel version doesn't do newlines
- Enable `setversion` for `install.sh`, it may fix #173 and fix #204 actually.
- Enable using user provided `modprobed.db` databases, to compile stripped down kernels for friends.
What do you think of all this ?

Some extra features for convenience 

---

install.sh
linux-tkg-config/prepare

Since the moment in which .config is created was changed, I transferred the Debian and Ubuntu workarounds to Prepare, it did not compile because it could not find the .conf when doing "sed"

 Fix Debian / Ubuntu compile due to .config

---

linux-tkg-config/prepare

On my machine, the kernel fails to build when srcdest is set in makepkg. My solution was to check the source folder and extract the upstream patch if the extracted patch is missing.
I am open to any changes.

Arch: Fix failure to extract kernel patch when srcdest is set in makepkg.conf

---

customization.cfg
install.sh

Hello!
Here I am for another round of improvements on `install.sh`. On the menu:
- Now compiling `bindeb-pkg` and `binrpm-pkg` instead of `deb-pkg` and `rpm-pkg`. When I first implemented it I thought the source code ones are needed for DKMS things. But afaik only the headers are needed. It makes the packaging process, after compilation, way faster.
- Git shallow remote fetching wasn't optimal. Fixed that
- Handling two remotes in Git wasn't done properly, fixed that.
- A few uses of reggex'es to makes conditions smaller.
I tested my changes (except on Suse, I got lazy) and I think it's all good to go!

install.sh: improve git fetching and stop producing source code packages

---

install.sh

Weirdly enough, I expected the kernel headers to be contained in the `kernel-headers` RPM packages. But they are actually in `kernel-devel`. So obviously that broke DKMS, and now it should be fixed!. Although we are back to using the lenghty `make rpm-pkg`.
I checked what's inside the DEBs and my change should work since `linux-headers` DEB package does actually contain the headers where DKMS wants them.
Closes: #230
Closes: #229

Fix DKMS for RPM distros

---

README.md
customization.cfg
install.sh

Hello,
This is  something I personally use on my Gentoo, which is basically the generic way to install the kernel:
```shell
sudo make modules_install
sudo make install
```
I added two more commands since it's what I personally use:
```shell
sudo dracut --hostonly --kver $_kernelname
sudo grub-mkconfig -o /boot/grub/grub.cfg
```
I don't know if it can be useful for others. What do you think ?

install.sh: Add convenience script for generic install

---

customization.cfg
linux-tkg-config/prepare

Fix: make Arch be able to use `_configfile` because the wrong path was being used. I fixed also a wrong use of `_msg2` I think.
Also, add `yes ""` to all the `make` calls, sometimes, I get prompts.

Fix: make Arch be able to use _configfile

---

README.md
install.sh
linux-tkg-config/prepare

Hello,
I was kinda expecting things to Just Work™ with the winesync changes. But it was not the case, it was simply not working for non-arch:
- The header in `/usr/include/linux/winesync.h` was not installed, thanks (#sarcasm) to my previous change to make things faster for DEB and RPM distros that already got partly reverted. Now it is fully reverted for them. And I added installing those files for the Generic approach
- Install the `winesync.rules` file "manually". For now that file can only be cleaned up manually. I do not think it's a big deal: it's only used by us, and if we need to change it I will add an update step to the `install.sh` script.
- Clean up the `winesync.rules` file on exit.
That's about it. Maybe I still miss something to make things work properly between `wine-tkg` …

Fix winesync for non-arch distros

---

customization.cfg
linux-tkg-config/prepare

Seeing as #239 nixed the `yes "" |` solution to Tk-Glitch/PKGBUILDS#404, I looked for another way to prevent the prompts. As @Tk-Glitch mentioned that adding the entries wasn't successful, I was convinced that there is a bug in `make localmodconfig`, and stepped through the Perl script for a few hours.
In the end, though, it seems that adding those two config lines fixes the issue just fine. I still don't really understand why this occurs, but this indeed should be better than piping newline key presses to `make`.

prepare: Prevent config prompt w/ modprobed-db.

---

PKGBUILD
README.md
install.sh
linux-tkg-config/prepare

After [my PR and discussion with Graysky2](https://github.com/graysky2/kernel_compiler_patch/pull/73), he changed the repository's name to `kernel_compiler_patch`. So we need to reflect the changes. I have not tried on Arch but I suppose I didn't miss anything, I changed all the occurrences of the URL.
This closes #259

Change to new name for Graysky march repository

---

linux-tkg-config/prepare

Hello again!
I discovered that entering any text string to prompts from `_prompt_from_array` in `prepare` actually makes it chose something although it shouldn't and should ask again. This should fix it.
Adel

prepare: restrict user input to digits in _prompt_from_array

---

PKGBUILD
customization.cfg

as the title says this just adds the option to not strip the vmlinux file in case you need debug tools like fadd2line

Make vmlinux stripping optional 

---

README.md

I created an `anbox-support` package which takes care of every step needed to get Anbox running without having to do manual changes to the filesystem. -> https://aur.archlinux.org/packages/anbox-support
Also, `anbox-git` recently got some changes - one of them being `/usr/lib/systemd/system/dev-binderfs.mount` being shipped which mounts binderfs without further intervention. It might be good to reflect that in the README as well.

Changes to Anbox instructions

---

customization.cfg

This PR adds 5.14 to the comment above the `_version` option in customization.cfg

Add 5.14 to allowed versions

---

install.sh

My KUbuntu installation turned out to lack `libelf-dev`, causing build error. I originally wanted to simply add it to Ubuntu package list, but then noticed that Debian option already includes it.
Since there's no harm in trying to install already installed packages, I've just merged two codepaths to use Debian's more extensive package list.

Unify Ubuntu and Debian dependency installation

---

linux-tkg-config/prepare

Thanks to @cpw the boot issues reported in Ubuntu have been figured out!
The issue was that Ubuntu's initramfs generation tool doesn't play nice with zstd compressed modules... Who knew. The fix also involves Debian, although I don't know if it's the same tool or not.
Adel
Closes: #327
Closes: #322

Fix boot issues in Ubuntu (and potentially Debian)

---

README.md

I tested the USE flag change from #323 and in the end it's not needed as I could successfully compile without the `default-compiler-rt` USE flag.

README: Gentoo: remove inaccurate dependency on a Clang use flag

---

PKGBUILD
customization.cfg
linux-tkg-config/prepare
linux-tkg-patches/5.13/0007-v5.13-futex_waitv.patch
linux-tkg-patches/5.14/0007-v5.14-futex_waitv.patch
linux-tkg-patches/5.15/0007-v5.15-futex_waitv.patch

Not enabled by default since this make currents public Wine/Proton builds with old fsync interfaces broken.
https://github.com/ValveSoftware/wine/pull/128
https://github.com/andrealmeid/futex_waitv_patches

linux513/514/515-tkg: Add futex_waitv() patchset from 5.16 as a toggle option

---

PKGBUILD
linux-tkg-config/prepare
linux-tkg-patches/5.13/0007-v5.13-fsync1_via_futex_waitv.patch
linux-tkg-patches/5.14/0007-v5.14-fsync1_via_futex_waitv.patch
linux-tkg-patches/5.15/0007-v5.15-fsync1_via_futex_waitv.patch

Adds https://gitlab.collabora.com/tonyk/linux/-/commit/b70e738f08403950aa3053c36b98c6b0eeb0eb90 to facilitate the transition.
I didn’t do any performance measurements, I just made sure it works for older Wine builds.
Actually has the same purpose as https://github.com/Frogging-Family/linux-tkg/commit/caad3e526dfdd96dc28e39ee071e9576fffe3a5c

Improve futex_waitv compatibility with Fsync1

---

customization.cfg
linux-tkg-config/prepare

it looks like there won't be any futex-waitv backports for more older kernels anytime soon, so need to fix the patching behavior of previously existing patches.

Correct applying fsyncs patches on kernels 5.12 and below

---

linux-tkg-config/prepare

Sorry, it looks like this check does not work properly,
but all these checks can be omitted due to 3462554540a75f346bd65a73ecd458fbfe21da29 in which the behavior of the script has changed.
This way it will simplify the script and fix the problem at the same time.

prepare: Fix and Cleanup some unnecessary checks related to Futex2

---

PKGBUILD
linux-tkg-config/prepare
linux-tkg-patches/5.16/0007-v5.16-fsync1_via_futex_waitv.patch

Simple editing https://gitlab.collabora.com/tonyk/linux/-/commit/b70e738f08403950aa3053c36b98c6b0eeb0eb90
(move `kernel/futex.c` changes to `kernel/futex/syscalls.c`)
Ignore `_futex_waitv` toggle and changing the priority towards `fsync1_via_futex_waitv.patch` instead of `fsync.patch` to 5.16+ kernels.
Let me know if this interferes with maintenance plans.

Add Fsync1 patchset for 5.16-rc

---

linux-tkg-config/prepare

fixes #371
Kernel (5.15.5) builds and boots (on Fedora 35, using `_lto_mode="full"`).

set LTO_NONE=y/n according to _lto_mode choice

---

PKGBUILD

So the resolve_btfids fix for DKMS modules in 5.16 was broken, it just didn't work. Both I and flgx on Discord confirmed it. I tried every way I could imagine to tweak just that line, so then I wrote an if-then like:
```
if [[ $_basever == 516 ]]; then
install -Dt "$builddir/tools/bpf/resolve_btfids" tools/bpf/resolve_btfids/resolve_btfids
fi
```
And that worked, but it was bothering me that your case statement wasn't working. After some tweaking I figured out it was int he wrong place. 
```
case $_basever in
516)
;;
*)
install -Dt "$builddir/tools/bpf/resolve_btfids" tools/bpf/resolve_btfids/resolve_btfids
;;
esac
```
Leads to it not doing anything at all. I confirmed this with `-Dvt` and there is no installing of anything. It' needs to be in the `516)` array. So I did that. And now it …

Fix resolve_btfids fix

---

README.md

Hello,
Following #356, a little update to the README to clarify that dependencies need to be manually installed for the generic install.
Adel

README: Generic Install: state that deps need to be manually installed

---

customization.cfg
install.sh
linux-tkg-config/prepare

- Resolves #264 
- Added `_preempt_rt` option.
- Added `_preempt_rt_force` option.
- Changed some `typeset` variables into globals.
This PR pulls the patches from [upstream RT](https://cdn.kernel.org/pub/linux/kernel/projects/rt/) and then applies them as early as possible. There are checks to see if upstream supports the kernel version being compiled and the check for kernel subversion can be bypassed with `_preempt_rt_force=1`.
To maintain the new feature, updating the entries in `_rt_subver_map` and `_rt_rev_map` will be enough for most cases.

Add support for RT patches

---

linux-tkg-config/prepare

remove "-full" from end as it doesn't seem to be present anymore (wasn't ever for 5.17 and recently changed for 5.16 too)
https://github.com/CachyOS/cacule-cpu-scheduler/commit/c28a7acf306a9d7ebcb2adb124acce6fb585ce0d

fix cacULE 5.16+ patch file name

---

linux-tkg-config/prepare

A little quality of life change that I wanted to implement long ago... Before the big overhaul I made to `prepare` it used to state which kernels were EOL.
I also automated that default index change so the default version in the prompt is a non-rc version.
This change shouldn't interfere with the RT stuff but I did not test it.
That's it !
Adel

Separate actively maintained kernels from EOL ones in prompts

---

.github/workflows/auto-update-kernel-versions.yml
.gitignore
PKGBUILD
linux-tkg-config/prepare
update-kernel-versions.sh

Hello!
I finally finished this work. So here's how this works:
- There's a script at the root of the repo, called `update-kernel-versions.sh`, that anyone can use on his own local copy of `linux-tkg` to bump versions automatically
- It uses `git ls-remote` to fetch latest tags, and sources the `prepare` script to compare whats on the repo and what's upstream
- If upstream offers a newer version, it changes
- The `prepare` script with the newer numbers
- Updates `PKGBUILD` sha sums by downloading both the older and newer archives to know which sha sum to replace with the newer one
- rc-to-release changes are also taken care of, you need to always put the patch shasum on an rc kernel to `#upcoming_kernel_patch_sha256` (I was out of ideas for a better naming) so it can be found and replaced …

Implement Github workflow to automatically bump kernel versions

---

install.sh
linux-tkg-config/prepare

This is the fix #438, with a small update to `install.sh` to have fewer lines of code and I also made `prepare` verbose about graysky's patches so we notice earlier if something is off.
Adel.

Fix cpu-opt patch in "install.sh" and make "prepare" verbose about it

---

README.md

Small additional information for the Arch install, to close one issue.
Closes: #440

README: Arch: specify `base-devel` requirement and redirect to wiki

---

linux-tkg-config/prepare

Fixes the following error:
/usr/share/makepkg/util/message.sh: line 69: printf: `B': invalid format character
and the patch not being applied because of a wrong file name.

Fixes for the recent cpu uarch changes

---

linux-tkg-config/prepare

Also just some general cleanup since this change :) as well as removing the LibreSSL function, since Void switrched to OpenSSL a while ago.  see: https://github.com/void-linux/void-packages/commit/a1e8089952113bddca256822a306f9ee7c894493

Void package now uses upstream kernel patch function

---

README.md

Updated the README to better suit that DKMS v3.0.2 and later handle clang / llvn out of the box.
Since DKMS v3.0.2 still is quite recent perhaps the warning should stay a bit longer.

Updated README.md to reflect DKMS Clang / llvm support

---

.gitignore
install.sh
linux-tkg-config/prepare
update-kernel-versions.sh

This makes it easier for people to open issues as we will ask them to attach every file in the "logs" folder that contains the logs for only the last build : 
-  a copy of `customization.cfg` that were used for the last build
- `prepare.log` 
-  the full output in the shell
- in `install.sh`, this is achieved with the `script` command.
- I couldn't firgure a seamless way for Arch people: to obtain the shell-output.log, we will ask them to do it by hand: `makepkg [args] | tee shell-output.log`
- system information (distro, version of `clang` and `gcc`), am I missing something here ?
these files have the `.txt` extension so they can easily be drag & dropped into Github issues.
Please make an issue template (I do not have permissions to do that) that:
- Asks people to describe their issue …

Bug reports: create "logs" folder and populate it at each run

---

.gitignore
update-kernel-versions.sh

Partially replace downloading original files to checking with kernel.org checksum autosigner and sha256sums.asc
addition to https://github.com/Frogging-Family/linux-tkg/pull/432
adds a GnuPG dependency, but as far as I understand the current Github workflow should support this:
https://github.com/actions/virtual-environments/blob/ubuntu20/20220508.1/images/linux/Ubuntu2004-Readme.md

update-kernel-versions.sh: Utilize sha256sums.asc

---

PKGBUILD

The hash for linux-5.18.tar.xz is incorrect, added the correct hash.

Fix hash for 5.18

---

customization.cfg

It has just been bumped from rc7 to the release (79e921e86acfc28e6c1ca73d555ef289b788f166)

cfg: Add 5.18 to kernel list

---

linux-tkg-config/prepare

With more than one user kernel config fragment (*.myfrag files) the application of fragments is seemingly random based on find command output making incremental deliberate config fragment application impossible.
This PR adds ascending alphabetical sort operation on top of the find result (array of found files) when searching for user fragments so that fragments are later applied to default kernbel config in alphabetical order.

Predictable alphabetically sorted user fragment application

---

linux-tkg-config/prepare

Enables use of the [TaskType Scheduler](https://github.com/hamadmarri/TT-CPU-Scheduler) with linux-tkg, utilising patches from the CachyOS project (by @ptr1337). 
I have successfully built 5.17 and 5.18 with the TT scheduler, and am currently running TT 5.18 with no issues.
Fixes #502

Add support for TaskType Scheduler

---

README.md

Like this users are informed of the current issues and can decide in trying `linux-tkg` with that in mind.

README: notify about issues in DEB and RPM based distros

---

linux-tkg-config/prepare

Given that the `--output-dir` was only argument was added in cURL version 7.73.0 (released October 14th, 2020), Ubuntu 20.04 and distributions based on it (among others, I'm sure) do not yet have this argument in the version of cURL that they ship.
This pull replaces the `--output-dir` argument with shell redirection to enable use on the aforementioned distros.

Replace instances of `--output-dir` from curl commands

---

update-kernel-versions.sh

Prefer to take a list of kernels tags for rc branches from mainline git
- take actual kernel rc tags list
- remove unnecessary keyrings.
Fixes:
```
current version on repository 5.19.rc1 -> 1
upstream version 5.19-rc2 -> 2
Newer upstream
Updating rc kernel version in linux-tkg-config/prepare
Downloading the GZ tarball for linux-5.19-rc2
Updating kernel shasum in PKGBUILD
old kernel: c2d2400bbf52688a1d2d1e45171331ddbc69ba1c3864e922c1c3f5b546b4d21b
new kernel: 530cb48a3bd084367d65f89a3e52af90676e155a65c39d3967726a5a4337339b
```

update-kernel-versions.sh: Sync with kernel rc tags list

---

customization.cfg
linux-tkg-config/prepare

Allows users to select the TaskType scheduler for the 5.19rc (tested to build and boot successfully).
Also allows enabling the High HZ patch for 5.15 in the config (solves #532). I do not personally use this patch, but I figure there is no harm in giving the option to those who want it (again, able to build and boot this configuration successfully).
If changes should be required for the implementation of the TT High HZ patch, I am happy to make them upon request.

Enable TT for 5.19rc and TT High HZ patch for 5.15

---

linux-tkg-patches/5.19/0008-5.19-bcachefs.patch

- Update bcachefs for 5.18
- Add bcachefs for 5.19
- Include module compilation fix, but still recommend to built it with =y right now
Signed-off-by: Peter Jung <admin@ptr1337.dev>

update bcachefs for 5.18, add bcachefs for 5.19, include module-fix

---

update-kernel-versions.sh

sha256sums.arc is not generated for new major RC
fixes: https://github.com/Frogging-Family/linux-tkg/runs/7843819575?check_suite_focus=true#step:3:19
this gives an extra line from `cut`, but should work fine.
it also looks like `curl` returns 0 if the download fails =\ , so the previous checks don't work properly.

update-kernel-versions.sh: Avoid sha256sums checks at new major RC

---

install.sh

I ran the script and many moments later, I was disappointed because I got the error `sudo: command not found`. This is because I use `doas` instead. Some people use `doas` or `su` instead of `sudo` so they do not have it installed. This change should automatically detect if the user has sudo installed, and if it is not, check if doas is installed, then check if su is installed.

Support `doas` and `su` for root authentication

---

linux-tkg-config/prepare
linux-tkg-patches/6.0/0007-v6.0-winesync.patch

small change for smooth applying
Fixes https://github.com/Frogging-Family/linux-tkg/issues/612
also respect https://github.com/Frogging-Family/linux-tkg/pull/591 and make winesync workarounds more stable
Resolves https://github.com/Frogging-Family/linux-tkg/issues/604

linux60: Fix Winesync patchset for 6.0-rc6

---

linux-tkg-patches/5.10/0013-fedora-rpm.patch
linux-tkg-patches/5.11/0013-fedora-rpm.patch
linux-tkg-patches/5.12/0013-fedora-rpm.patch
linux-tkg-patches/5.13/0013-fedora-rpm.patch
linux-tkg-patches/5.14/0013-fedora-rpm.patch
linux-tkg-patches/5.15/0013-fedora-rpm.patch
linux-tkg-patches/5.16/0013-fedora-rpm.patch
linux-tkg-patches/5.17/0013-fedora-rpm.patch
linux-tkg-patches/5.18/0013-fedora-rpm.patch
linux-tkg-patches/5.19/0013-fedora-rpm.patch
linux-tkg-patches/5.4/0013-fedora-rpm.patch
linux-tkg-patches/5.7/0013-fedora-rpm.patch
linux-tkg-patches/5.8/0013-fedora-rpm.patch
linux-tkg-patches/5.9/0013-fedora-rpm.patch
linux-tkg-patches/6.0/0013-fedora-rpm.patch

Current mkspec patches do not make `kernel` package provide `kernel-uname-r` package, which is e. g. necessary to build nvidia kmods manually.

fix mkspec patches

---

customization.cfg
linux-tkg-config/prepare

The linux-tkg has a `_tickless` parameter which controls how the scheduling-clock interrupts behaves in the kernel. There is a Full dynticks mode is described as "Can provide better performance in many cases". The problem is that it is not specified here that without passed `nohz_full` kernel parameter it works the same way as Idle dynticks which is described in kernel option description. Even so, Full dynticks only makes sense when there is one single task running on the processor core (see https://docs.kernel.org/timers/no_hz.html?highlight=tickless#omit-scheduling-clock-ticks-for-cpus-with-only-one-runnable-task) and there are no other tasks to switch. I think this case may be relevant only when isolating CPUs, but not for desktop tasks or games, but I could be wrong.

Clarify the description of the tickless parameter

---

linux-tkg-config/prepare

This adds additional git repo from Linus Torvalds to `linux-src-git` which allows to switch to and evaluate recent -rc kernels immediately after commited by Linus.

Add Torvalds' git repo for faster -rc kernel evaluation

---

customization.cfg
linux-tkg-config/prepare

The cpu opt patches have support for raptorlake, meteorlake, and zen4 cpus now. GCC13 requirements were mentioned in the customization.cfg

Update CPU opt lists to include raptorlake, meteorlake, and zen4

---

linux-tkg-patches/6.0/0009-prjc_v6.0-r0.patch

Hey Mr. Etienne, since [mglru is enabled by default](https://github.com/Frogging-Family/linux-tkg/blob/b8835ca20232e4bbf0738bd4e25bcffeb917ad57/customization.cfg#L162) it is worth adding support in BMQ/PDS

Enable MGLRU support in prjc

---

linux-tkg-patches/5.15/0007-v5.15-fsync1_via_futex_waitv.patch

addition to https://github.com/Frogging-Family/linux-tkg/pull/676
Fixes https://github.com/Frogging-Family/linux-tkg/issues/679

linux 5.15.y: Update compatibility fix for old Fsync ABI

---

.github/workflows/build-current-kernel-arch.yml
PKGBUILD
customization.cfg
install.sh
linux-tkg-config/prepare

After our little discussion [here](https://github.com/Frogging-Family/linux-tkg/commit/f4324da8a1f4bad740ac66aeefb652a061666a49), I am opening this PR to improve and unify the `PKGBUILD` and the `install.sh` approach with respect to dealing with kernel sources.
Now:
- We can customize where to put the compressed kernel sources (a git bare repo, size around ~400MB)
- We can customize where to put the "checked out" kernel sources, including a tmpfs folder if wanted.
The cool thing @Tk-Glitch is that you can try to have the compressed kernel sources still in the HDD on your machine and see if it actually improves your compile times, since  it's compressed, and creating a worktree to tmpfs should be faster than cloning ? Let's see !
I need to test on Ubuntu and Fedora to see that I didn't …

Improve customization of source and work folders

---

install.sh
linux-tkg-config/prepare
linux-tkg-patches/5.10/0013-fedora-rpm.patch
linux-tkg-patches/5.11/0013-fedora-rpm.patch
linux-tkg-patches/5.12/0013-fedora-rpm.patch
linux-tkg-patches/5.13/0013-fedora-rpm.patch
linux-tkg-patches/5.14/0013-fedora-rpm.patch
linux-tkg-patches/5.15/0013-fedora-rpm.patch
linux-tkg-patches/5.16/0013-fedora-rpm.patch
linux-tkg-patches/5.17/0013-fedora-rpm.patch
linux-tkg-patches/5.18/0013-fedora-rpm.patch
linux-tkg-patches/5.19/0013-fedora-rpm.patch
linux-tkg-patches/5.4/0013-fedora-rpm.patch
linux-tkg-patches/5.7/0013-fedora-rpm.patch
linux-tkg-patches/5.8/0013-fedora-rpm.patch
linux-tkg-patches/5.9/0013-fedora-rpm.patch
linux-tkg-patches/6.0/0013-fedora-rpm.patch
linux-tkg-patches/6.1/0013-fedora-rpm.patch
linux-tkg-patches/6.2/0013-fedora-rpm.patch

While trying to fix the `mkspec` script within the kernel, I discovered a few things
- Fedora imposes various hardening flags and other bloat that we could avoid, 
- Fedora produces some debug files that conflict with other `tkg` kernels
It took me some time to find documentation to disable all that, but it's done. There also was mistake in the `install.sh` where I was using the wrong work dir path variable, people shouldn't have been able to build for Fedora without giving absolute paths since we merged the work dir change MR.
Adel

Various fixes for the RPM target

---

linux-tkg-patches/6.2/0009-prjc_v6.2-r0.patch

Sync PRJC Scheduler with upstream.
Please consider to enable `CONFIG_PSI_DEFAULT_DISABLED` as default to avoid issues with this patchset.
This issue is still present

6.2: Update prjc patchset

---

linux-tkg-patches/6.2/0003-glitched-cfs-additions.patch
linux-tkg-patches/6.3/0003-glitched-cfs-additions.patch

Sorry, I should have checked the changes more thoroughly before pushing.

linux 6.{2,3}.y: Fix wrong patch

---

install.sh

I fixed the issue #751
- Cause
install.sh uses rpm-pkg to build rpms for Fedora.
The rpm-pkg makes diff.patch from the patched source tree, pack it into the src.rpm, then extract vanilla source and apply diff.patch.
For making diff.patch, "git diff HEAD" is used. But "git diff HEAD" can not detect modified files without "git add".
So, new files from patches are not created after applying the patch during rpm-pkg build.
- Solution
I added "git add" into the install.sh for detecting the patched files before rpm-pkg.
(I also added "dnf install perl" for the build dependency)

Fix install.sh for fedora

---

.github/workflows/build-current-kernel-arch.yml
README.md
customization.cfg
linux-tkg-config/prepare

officially no longer active since months.
basically no longer active since ages.
an alternative is available and in active development (also recommended by anbox), no need to keep this here

Remove anbox option

---

linux-tkg-patches/6.4/0008-6.4-bcachefs.patch
linux-tkg-patches/6.5/0008-6.5-bcachefs.patch

- The `printk` calls in `test_free`/`test_malloc` (called from `madvise`) were accidentally left in by the author and can randomly cause major performance problems even if none of the bcachefs options are enabled. They are triggered when `madvise` is called with `MADV_COLLAPSE`. Thousands of these messages attempt to get printed. `dmesg` seems to never stop printing. I was getting messages in journal:
```
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 …
```

glitched-cfs-additions: fix for 6.5.2, remove performance-killing printk calls in bcachefs patches

---

linux-tkg-patches/6.5/0003-eevdf.patch

Necessary patches to support BORE 3.2.8: https://github.com/firelzrd/bore-scheduler/commits/main
Source: https://git.kernel.org/pub/scm/linux/kernel/git/peterz/queue.git/log/?h=sched/eevdf

6.5: EEVDF adaptation to BORE 3.2.8

---

install.sh

overriding config values through environment variables wasn't working because the script call was resetting them before
they were saved
also, the external config file was getting sourced twice

install.sh: fix handling of env var config overrides

---

linux-tkg-config/prepare

Add Fedora kernel configuration for SELinux. This prevent relabel of most files when booting a kernel without this feature.

In case of Fedora: modify kernel configuration to add SELinux. Fix #383

---

linux-tkg-patches/6.6/0001-mm-Support-soft-dirty-flag-reset-for-VA-range.patch
linux-tkg-patches/6.6/0002-mm-Support-soft-dirty-flag-read-with-reset.patch

This adds missing write watch patches I've ported over from 6.1 to 6.6. I'm using this in my own daily-drive 6.6 LTS kernel.
See-also: https://github.com/kakra/linux/pull/30

6.6: Add patches for WRITE_WATCH support in Wine

---

linux-tkg-config/6.5/minimal-modprobed.db
linux-tkg-config/6.6/minimal-modprobed.db

Fixes mkinitcpio failing due to missing drm_privacy_screen_register function.
Fixes #854.

Add thinkpad_acpi to the diet modprobed-db config

---

linux-tkg-patches/6.7/0007-v6.7-winesync.patch

This PR is a simple patch that fixes patch application for the winesync patch for kernel 6.7. There was an error in applying the patch to `tools/testing/selftests/Makefile`.

Fix winesync patch application for 6.7

---

install.sh

we reverted back to `deb-pkg` and `rpm-pkg` in the past to support `winesync`: it requires a header in `/usr/include/linux` and that header is in the `src` RPM/DEB packages, but I believe we can simply just copy that single required header instead.
Closes: #905

install.sh: DEB: RPM: bring back bindeb-pkg and binrpm-pkg targets

---

linux-tkg-config/6.8/minimal-modprobed.db
linux-tkg-config/6.9/minimal-modprobed.db

I just compiled a full 6.8 kernel to get bluetooth working (using my own `modprobed-db` db) and just added what was missing our current `minimal-config` files in 6.8 and 6.9

6.8 & 6.9: update diet db

---

linux-tkg-config/prepare
linux-tkg-patches/6.9/0009-prjc_v6.9-r0.patch

Added commits ab3f0a90..ef162b48 from [alfredchen/linux-prjc/linux-6.9.y-prjc](https://gitlab.com/alfredchen/linux-prjc/-/commits/linux-6.9.y-prjc/?ref_type=heads) on top of the linux-tkg [0009-prjc_v6.8-r5.patch](https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-patches/6.8/0009-prjc_v6.8-r5.patch)
This doesn't address _rr_interval, which has been non-functional as a customizable option in linux-tkg for the past few PrjC versions.
Update: tested working on kernel 6.9-rc7 (and -rc6)

Add Project-C v6.9-r0

---

install.sh

The `grubby` package conflicts with systemd-boot and the corresponding `sdubby` package. [Systemd-boot is an officially supported boot loader since Fedora 39](https://fedoraproject.org/wiki/Changes/cleanup_systemd_install).
Any installation with grub2 has grubby installed by default anyway.
fixes #952

remove `grubby` from required Fedora packages

---

customization.cfg
linux-tkg-config/prepare

CachyOS sets this to 100000, default is 200000
Description reads as:
```
+config MIN_BASE_SLICE_NS
+	int "Default value for min_base_slice_ns"
+	default 2000000
+	help
+	 The BORE Scheduler automatically calculates the optimal base
+	 slice for the configured HZ using the following equation:
+	 
+	 base_slice_ns =
+	 	1000000000/HZ * DIV_ROUNDUP(min_base_slice_ns, 1000000000/HZ)
+	 
+	 This option sets the default lower bound limit of the base slice
+	 to prevent the loss of task throughput due to overscheduling.
+	 
+	 Setting this value too high can cause the system to boot with
+	 an unnecessarily large base slice, resulting in high scheduling
+	 latency and poor system responsiveness.
+
```

Add min_base_slice_ns for BORE scheduler

---

linux-tkg-config/prepare

The patch name was changed 2 weeks ago. graysky2/kernel_compiler_patch@44598c402184de0de4c9f0addce5771bf0eae0c4

Update the Graysky's per-CPU-arch native optimizations patch name

---

linux-tkg-patches/6.13/0009-prjc_v6.13-r0.patch

Fixes #1067, Fixes #1068 
PDS and BMQ fail compilation since PREEMPT_LAZY was added in 6.13.

refactor prjc for 6.13

---

.github/workflows/arch-builder.yml
.github/workflows/fedora-builder.yml
.github/workflows/ubuntu-builder.yml
README.md
customization.cfg
linux-tkg-config/prepare

remove waydroid option, now enabled in arch config

---

customization.cfg
linux-tkg-config/prepare

This MR does two things
1. Make `_git_mirror` in `customization.cfg` accept directly git links
2. Make `_version` in `customization.cfg` accept any git tag that is on the remote currently configured.
Needs testing
Fixes #1057

Flexible git remotes

---

PKGBUILD
customization.cfg
install.sh

A very good gun to shoot yourself in the foot.
We can also hard code it in the `Makefile`, so even `dkms` modules pick them up. I think DKMS doesn't support passing compilers flags, at least I couldn't find how.
Do we want this in ? I think it works in non-Arch already because the environment doesn't get cleared.

customization: support forwarding user provided compiler flags

---

install.sh

linux-tkg wasn't compiling in my updated system Debian 13 trixie. So I just edited libncurses5-dev to libncurses-dev then it compiled again. libncurses5-dev package is deprecated now for both Debian 12 and 13. As for Ubuntu, I tested installing libncurses-dev in my Ubuntu 24.04 VM and it worked good, so I guess it'll work in any recent Ubuntu (LTS) or Debian, and fix the issue for Debian 13 (testing for now, but coming to be stable really soon).

debian/ubuntu: libncurses5-dev deprecation

---

linux-tkg-patches/6.10/0002-clear-patches.patch
linux-tkg-patches/6.11/0002-clear-patches.patch
linux-tkg-patches/6.12/0002-clear-patches.patch
linux-tkg-patches/6.13/0002-clear-patches.patch
linux-tkg-patches/6.14/0002-clear-patches.patch
linux-tkg-patches/6.15/0002-clear-patches.patch
linux-tkg-patches/6.16/0002-clear-patches.patch
linux-tkg-patches/6.17/0002-clear-patches.patch
linux-tkg-patches/6.8/0002-clear-patches.patch
linux-tkg-patches/6.9/0002-clear-patches.patch

It was removed since gregkh/linux@689237ab37c59b9909bc9371d7fece3081683fba and broke my kernel building. I don't know why it successful in release page.

Remove the no longer existing intelfb

---

customization.cfg
linux-tkg-config/prepare

I had to build a kernel offline (to disable modprobed-db) but realized it was impossible without some tweaks: here they are
I tested thins on both the `./install.sh` approach and `makepkg`

Add option to build kernels fully offline
