- linux58-tkg/PKGBUILD
- linux58-tkg/linux58-tkg-config/prepare
- linux58-tkg/linux58-tkg-patches/0009-glitched-bmq.patch
- linux58-tkg/linux58-tkg-patches/0009-glitched-ondemand-bmq.patch
- linux58-tkg/linux58-tkg-patches/0009-prjc_v5.7-r3.patch
> Add rebased BMQ from 5.7.

- linux57-tkg/customization.cfg
- linux57-tkg/install.sh
Hello!
I forgot to do some changes, so here they are :D
> linux57: extra changes to Ubuntu install script that have been forgotten

- linux58-tkg/PKGBUILD
- linux58-tkg/linux58-tkg-config/prepare
- linux58-tkg/linux58-tkg-patches/0009-bmq_v5.8-r0.patch
- linux58-tkg/linux58-tkg-patches/0009-glitched-bmq.patch
- linux58-tkg/linux58-tkg-patches/0009-glitched-ondemand-bmq.patch
> Add rebased BMQ from 5.8

- linux54-tkg/PKGBUILD
- linux54-tkg/linux54-tkg-config/prepare
- linux57-tkg/install.sh
- linux57-tkg/linux57-tkg-config/prepare
- linux58-tkg/PKGBUILD
- linux58-tkg/linux58-tkg-config/prepare
Note: I think this statement is true if the answer contains "y" or "Y"
> Allow using upper-cased "Y" to answer questions

- linux59-rc-tkg/PKGBUILD
- linux59-rc-tkg/linux59-tkg-config/prepare
Updated to rc6 sha256sums and all confirmed working on my end
> Doctorwho1909 5.9 rc6

- linux58-tkg/linux58-tkg-patches/0002-clear-patches.patch
https://github.com/clearlinux-pkgs/linux.git
Signed-off-by: Juuso Alasuutari <juuso.alasuutari@gmail.com>
> linux58-tkg: Update clear linux patches to upstream tag 5.8.12-989

- install.sh
This PR #62  was merged after starting the work on the unified build script.
Also add 5.10 RC to opt_ver case.
> Add back #62 Add initial -rc support to the install.sh script.

- install.sh
Fix MuQSS illegal character uppercase in source package name for .deb build
Fix _cpusched not being sourced for package name
Fix llvm not in package name when using llvm
> install.sh: Fix LLVM build restart config

- README.md
Figured you may wanna add this to the readme so people don't go ahead and make configuration changes if its already an option.
> Add anbox to readme

- PKGBUILD
- linux-tkg-config/prepare
- linux-tkg-patches/5.11/0001-mm-Support-soft-dirty-flag-reset-for-VA-range.patch
- linux-tkg-patches/5.11/0002-mm-Support-soft-dirty-flag-read-with-reset.patch
- linux-tkg-patches/5.12/0001-mm-Support-soft-dirty-flag-reset-for-VA-range.patch
- linux-tkg-patches/5.12/0002-mm-Support-soft-dirty-flag-read-with-reset.patch
Needed for D3D12 APITracing under Wine
> Add mm-soft-dirty patchset from Paul Gofman

- install.sh
Apparently in the new versions of the kernel or some configuration that I do not know but with this it is solved, almost very similar to Debian.
> Fix compilation on Ubuntu due canonical-certs

- customization.cfg
- linux-tkg-config/prepare
> Add toggle for default TCP algorithm

- linux-tkg-config/prepare
No need to change checksumming to SHA1 anymore :)
> Void no longer uses LibreSSL, switched to OpenSSL

- PKGBUILD
- linux-tkg-patches/5.13/0007-v5.13-futex2_interface.patch
Add the futex2 patchset rebased by me
> linux513: Add futex2 patches

- linux-tkg-config/prepare
The bug hunt has officially started!
This closes #253
> prepare: handle properly optiprofile from `customization.cfg`

- install.sh
Hello,
I need this little thing with my (Gentoo) Generic install with Clang :D 
Thank you!
> install.sh: Generic + Clang: prompt to replace libunwind with llvm-libunwind

- PKGBUILD
> Update Kernel compiler patch URL

- README.md
- customization.cfg
- install.sh
- linux-tkg-config/prepare
Hello,
So everything is in the title, I did do some small fixes too. I tested on Ubuntu, Fedora and Gentoo. It all seems good!
Adel
> Improve Generic code path + Gentoo + tmpfs building

- customization.cfg
- linux-tkg-config/prepare
For manual intervention :frog:
> prepare: allow choosing oldconfig as the .config updating tool

- README.md
Hello,
Small update  for people who encounter #323 
Adel
> README: add dependency notes for Gentoo

- customization.cfg
- linux-tkg-config/prepare
Untested but I'm sure it works :frog:
> prepare: allow forcing LLVM_IAS

- PKGBUILD
- linux-tkg-config/prepare
- linux-tkg-patches/5.14/0009-prjc_v5.14-r3.patch
A little prjc bump: https://gitlab.com/alfredchen/projectc/-/blob/master/5.14/prjc_v5.14-r3.patch
> prjc-5.14: version bump

- linux-tkg-patches/5.14/0012-misc-additions.patch
Fixes #347. This is my first PR and I'm not used to hacking on the kernel so if there's anything wrong, please gently nudge me in the right direction :)
> fix Frogging-Family#347

- PKGBUILD
- linux-tkg-patches/5.16/0007-v5.16-winesync.patch
trivial rebase for smooth applying
> Add Winesync patchset for 5.16-rc

- README.md
A little fix to make the link actually clickable.
> Small Formating Error In ReadMe

- install.sh
Related to https://github.com/Frogging-Family/linux-tkg/pull/312
(I got impatient)
> also reordered them alphabetically, but that's not really a big change.
> Added schedtool to dependencies

- install.sh
Small fixes in `install.sh`
Closes: #352
> install.sh: quote every variable used in if statements

- PKGBUILD
- install.sh
- linux-tkg-config/prepare
And update to new naming scheme
This will fix #459 and close #461 
Signed-off-by: Adel KARA SLIMANE <adel.ks@zegrapher.com>
> cpu uarch patches: move download code to prepare

- PKGBUILD
> Added a placeholder for future 5.17 SHA256 sum

- PKGBUILD
A little PR to please @Sukid xD
I haven't tried it yet, please confirm that all is good.
Adel
> linux-5.16: add bcachefs patch

- PKGBUILD
- customization.cfg
- linux-tkg-config/prepare
- linux-tkg-patches/5.10/0007-v5.10-winesync.patch
- linux-tkg-patches/5.11/0007-v5.11-winesync.patch
- linux-tkg-patches/5.12/0007-v5.12-winesync.patch
- linux-tkg-patches/5.13/0007-v5.13-winesync.patch
- linux-tkg-patches/5.14/0007-v5.14-winesync.patch
- linux-tkg-patches/5.15/0007-v5.15-winesync.patch
- linux-tkg-patches/5.16/0007-v5.16-winesync.patch
- linux-tkg-patches/5.17/0007-v5.17-winesync.patch
- linux-tkg-patches/5.18/0007-v5.18-winesync.patch
kernel-side part of winesync/fastsync https://lkml.org/lkml/2021/1/17/312
source: https://repo.or.cz/linux/zf.git/shortlog/refs/heads/winesync4
> Update winesync patches

- linux-tkg-config/prepare
> prepare: move 5.16 to EOL

- update-kernel-versions.sh
Prefer to take a list of kernels tags for stables and longterm branches from `sha256sums.asc` instead git
This patch addition to https://github.com/Frogging-Family/linux-tkg/pull/515 and should solve the hashsums replacement issue when the script execution falls at a time while the kernel.org archive files are not yet available, but the list of tags from git is already fresh
(like https://github.com/Frogging-Family/linux-tkg/commit/79e921e86acfc28e6c1ca73d555ef289b788f166 did not update hashsum in PKGBUILD and https://github.com/Frogging-Family/linux-tkg/pull/519)
- prefer to take the list of kernels tags from `sha256sums.asc` as a guarantee that the files are available for download
- add `--retry 2` for all curl download commands
- output more information about the hashsums being …
> update-kernel-versions.sh: Depends more on sha256sums.asc

- customization.cfg
5.19 has been released from rc. (https://github.com/Frogging-Family/linux-tkg/commit/f8388b20ce68778f8799ed34f0b818b5a2e0ec60)
> cfg: add 5.19 to kernel version list

- README.md
- install.sh
- linux-tkg-config/prepare
- linux-tkg-patches/5.10/0013-fedora-rpm.patch
- linux-tkg-patches/5.11/0013-fedora-rpm.patch
- linux-tkg-patches/5.12/0013-fedora-rpm.patch
- linux-tkg-patches/5.13/0013-fedora-rpm.patch
- linux-tkg-patches/5.14/0013-fedora-rpm.patch
- linux-tkg-patches/5.15/0013-fedora-rpm.patch
- linux-tkg-patches/5.16/0013-fedora-rpm.patch
- linux-tkg-patches/5.17/0013-fedora-rpm.patch
- linux-tkg-patches/5.18/0013-fedora-rpm.patch
- linux-tkg-patches/5.19/0013-fedora-rpm.patch
- linux-tkg-patches/5.4/0013-fedora-rpm.patch
- linux-tkg-patches/5.7/0013-fedora-rpm.patch
- linux-tkg-patches/5.8/0013-fedora-rpm.patch
- linux-tkg-patches/5.9/0013-fedora-rpm.patch
Hello!
Great news today, I finally took time to go as deep as needed into the kernel scripts that make RPMs to fix the long standing issues we have. This PR should fix: 
- Conflicts with official packages
- Should compile just fine with `akmod-nvidia`
- Fixes the "unversionned obsoletes" issues
Adel
> RPM build: Fix several issues

- linux-tkg-config/prepare
It builds and boots just fine.
> Add TaskType to Linux 6.0

- linux-tkg-patches/6.0/0009-prjc_v6.0-r0.patch
I'm updating the Torvic9 prjc fork..
> Update tovic9 prjc sched to latest changes - 2:

- PKGBUILD
- install.sh
Okay,
A very shmol fix for #647 and I used the opportunity to offer support for the external config in `install.sh`.
That's it !
Adel
> PKGBUILD: sourcing order fix

- linux-tkg-patches/6.0/0010-lru_6.0.patch
Yuzhao posted his latest change to his personal repository..
https://github.com/yuzhaogoogle/linux/commits/mglru-6.0
Backup: http://web.archive.org/web/20221123173922/https://github.com/yuzhaogoogle/linux/commits/mglru-6.0
> Sync MGLRU with latest Yuzhao changes:

- linux-tkg-patches/6.0/0009-prjc_v6.0-r0.patch
Sup Etienne, finally Alfred updated the PDS/BMQ :smile:
> Update prjc 6.0r0 with latest official Alfred Chen

- linux-tkg-config/prepare
Simple change since the groundwork was laid out with our last PR. @ptr1337 is doing an awesome job keeping this patchset updated with current kernels.
> Add TaskType to 6.1

- linux-tkg-patches/5.15/0007-v5.15-futex_waitv.patch
following https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.86&id=fd8a10d44c11f8f53d640db6b97486045b7e0b81
Fixes: https://github.com/Frogging-Family/linux-tkg/issues/675
> linux 5.15.y: futex_waitv fixup

- README.md
Signed-off-by: Peter Jung <admin@ptr1337.dev>
> README: Add BORE to alternative schedulers

- linux-tkg-patches/6.3/0006-add-acs-overrides_iommu.patch
> linux 6.3 RC: fix ACS override patch causing an error

- linux-tkg-config/prepare
updated to include BORE scheduler, BORE patch is supporting linux 6.3
> Update prepare to include BORE Scheduler

- install.sh
- linux-tkg-config/prepare
- linux-tkg-patches/6.4/0013-fedora-rpm.patch
- linux-tkg-patches/6.5/0013-fedora-rpm.patch
Some fixes that were long overdue!
Adel
> Various fixes

- linux-tkg-patches/6.5/0003-eevdf.patch
Adding these 4 patches should fix the above mentioned error (#825)
> 6.5: Add new EEVDF patches for BORE 3.2.0 (fix #825)

- linux-tkg-patches/6.5/0003-eevdf.patch
See: https://git.kernel.org/pub/scm/linux/kernel/git/peterz/queue.git/commit/?h=sched/urgent
> 6.5: Add EEVDF urgent fix

- linux-tkg-patches/6.6/0003-eevdf.patch
Same situation as with PR #828.
> 6.6: EEVDF adaptation to BORE 3.2.8

- linux-tkg-patches/6.5/0004-eevdf-Disable-DELAY_DEQUEUE.patch
- linux-tkg-patches/6.6/0004-eevdf-Disable-DELAY_DEQUEUE.patch
Solution to problem #830 - only needed with EEVDF, as BORE-EEVDF already has this solution.
> EEVDF: Disable DELAY_DEQUEUE - fix #830

- linux-tkg-patches/6.6/0008-6.6-bcachefs.patch
Sync with https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c9d01179e185f72b20af7e37aa4308f4c7ca7eeb
> 6.6: Update bcachefs

- README.md
now that we have fixed selinux
> README: remove Fedora warning

- customization.cfg
> customization.cfg: update 'bcachefs' & 'mglru' notes

- linux-tkg-config/prepare
- linux-tkg-patches/6.6/0009-prjc_v6.6-r0.patch
- linux-tkg-patches/6.7/0009-prjc_v6.7-r0.patch
New PRJC patches for 6.6 and 6.7 have been released:
6.6: https://gitlab.com/alfredchen/linux-prjc/-/commits/linux-6.6.y-prjc
6.7: https://gitlab.com/alfredchen/linux-prjc/-/commits/linux-6.7.y-prjc
Closes: #868
> Add PRJC for 6.6 and 6.7

- linux-tkg-patches/6.7/0009-prjc_v6.7-r2.patch
> Add PRJC 6.7-r2

- linux-tkg-patches/6.8/0007-v6.8-winesync.patch
> 6.8: Fixup winesync patch

- install.sh
Noticed install.sh broke due to this being missed.
> Several improvements: quick fix

- install.sh
- linux-tkg-config/prepare
shell-output.log wasn't getting created at all, I was wondering why all the newest bug reports were not attaching it at all and started losing hope in humanity haha
> Non-arch: fix logging

- linux-tkg-patches/6.9/0013-suse-additions.patch
I was able to build the kernel with these changes.
Should fix https://github.com/Frogging-Family/linux-tkg/issues/939 and https://github.com/Frogging-Family/linux-tkg/issues/941 I guess.
> 6.9: Update patch for suse

- linux-tkg-patches/6.10/0013-suse-additions.patch
Tested on Tumbleweed with Linux 6.10 rc 6.
> Fix Suse build

- linux-tkg-config/prepare
>  6.10: Allow bore sched

- linux-tkg-config/prepare
- linux-tkg-patches/6.11/0009-prjc_v6.11-r0.patch
Added patch for project C for linux 6.11
> Project C for 6.11

- install.sh
Hopefully I didn't break anything, although I don't think so, tried quickly on my machine.
Fixes #1025
> install.sh: prompt for distro even when using 'config'

- customization.cfg
- linux-tkg-config/6.12/minimal-modprobed.db
- linux-tkg-config/6.13/minimal-modprobed.db
Some extra modules that I think should be added.
> Update diet modprobed-db

- .github/workflows/update-kernel-configs.yml
Little workflow to automatically update kernel configs, one thing less to bother with.
> ci: add workflow to update kernel config
